added vpktool
ValvePython/vpk pull request #2
Opened 2016-10-20 05:41 UTC by trevortomesh

I wrote a little script for a vpk extractor tool that might help people who aren't coders.

2016-10-20 16:49 UTC, rossengeorgiev commented
Hi @trevortomesh, that's a cool idea!!
Do you think you could develop this further into a more complete CLI tool?
It could use some options and flags. I can think of a few

* -x [path]  extract to directory
* -f --filter  regex filter for file path
* -i --info  print info about the vpk file, version, number of files etc
* -l --list  list files (file size, crc, file path)
* --verify   validate that files are correct
* --no-path   don't create directories, extract files in same directory

2016-10-20 16:53 UTC, trevortomesh commented
Sure -- it might take a while as I have my irons in a lot of fires... but, yeah.

2016-10-20 17:06 UTC, rossengeorgiev commented
Luckly the modules for this already exist and it's a matter of putting it together. `argparse` will do all the CLI stuff for you, then `vdf` and `regex`, and finally `os` to write stuff to disk in compatible way. Boom! You've got a cross-platform cli tool. Finally, add entry point to the setup file for `vdf`, so that when you install you will get the tool linked in bin and ready for use immediately.

2016-10-20 17:08 UTC, trevortomesh commented
I'd be happy to work on it further. Let me know if there's anything you'd want before accepting the pull request. :-)

2016-10-22 20:32 UTC, rossengeorgiev submitted a review, later dismissed
Need a shebang for python, so it can be executed directly.

`#!/usr/bin/env python`

2016-10-22 20:35 UTC, rossengeorgiev requested changes
Sure that would be nice. (testing github review process)

2016-10-22 20:35 UTC, rossengeorgiev commented on vpktool.py
> +# Easy VPK extractor
Need a shebang for python, so it can be executed directly.

`#!/usr/bin/env python`

2016-10-22 21:01 UTC, trevortomesh commented on vpktool.py
> +# Easy VPK extractor
Done.

2016-10-22 21:02 UTC, rossengeorgiev approved these changes

2016-10-22 21:04 UTC, trevortomesh commented on vpktool.py
> +# Easy VPK extractor
I think you need to approve the pull request as well.

2016-10-23 13:40 UTC, trevortomesh commented
I think you've still got to approve the pull request itself. :-p

2016-10-23 18:27 UTC, rossengeorgiev commented
@trevortomesh, I was testing the review functions. The PR is not ready to be merged yet. Do you plan to implement the things I've suggested in my previous comment? Will you be making unittests for vpktool?

2016-10-23 18:30 UTC, trevortomesh commented
Of course! I'll have to look into unit test in Python.

2016-10-23 18:36 UTC, rossengeorgiev commented
The module already has a test suite, so you can look into that. See the `Makefile` for how to run it. You will want to various function of the vpktool testable by putting into functions, so they can be imported and tested. Look at the my bullet point list above first. If you need any help just ask.

2016-10-23 19:56 UTC, trevortomesh commented
Great. Will do.

2016-12-29 05:12 UTC, rossengeorgiev commented
Closing due to inactivity

2016-12-29 05:12 UTC, closed without merging